type: poll
name: Poll
base: poll
module: poll
description: 'A <em>poll</em> is a question with a set of possible responses. A <em>poll</em>, once created, automatically provides a simple running count of the number of votes received for each response.'
help: ''
has_title: '1'
title_label: Question
create_body: '0'
custom: '0'
modified: '0'
locked: '1'
disabled: '0'
orig_type: poll
uuid: 26659425-53c7-4c1b-8c02-2a467dea0560
langcode: und
settings:
  node:
    submitted: '1'
    preview: '1'
    options:
      - status
      - promote
status: '1'